### ISSUE TITLE
Add Roundcube plugins

### ISSUE THREAD

**Issue by yurivanmidden** [instrumentisto/roundcube-docker-image#1]
Hi,
Is there a way to add more Roundcube plugins in this Docker image? Can I slipstream them with an environment variable, like `ROUNDCUBE_PLUGINS=['archive','managesieve']`?

Thanks.

**Comment by tyranron** [comment]
@yurivanmidden hi!

This image supports any environment variables that are used by Roundcube itself. Just specify them on container start.

But, as for plugins, I don't see the way they can be installed into this concrete image. You can just enable/disable plugins which are preinstalled into image. Those are just ones distributed with [Roundcube releases](https://github.com/roundcube/roundcubemail/releases). Nothing more.

If you need plugins which require additional installation - you should create your own image.  
This image may be used as `FROM` for your one. Just provide inside [your own `composer.json`](https://plugins.roundcube.net/), or edit existing one. And [install Composer and run `composer install`](https://github.com/instrumentisto/roundcube-docker-image/blob/525d95ed11c2319f0dfe145be0f0729b3296c1a5/1.3/fpm/Dockerfile#L66-L82).

**Comment by r3pek** [comment]
@tyranron i was looking for an image that supported "external" plugins, but the best roundcube image i found was this one.
Looking at the Dockerfile, you can support them on this image easily:
- Don't uninstall composer since you install it and then remove it.
- Suggest users to create a docker config with the information of composer.json and "mount" it on its location (/app/composer.json)
- Run composer update on the entrypoint shell script.

Not that difficult, but I'll make an image for myself if you end up not wanting to do it (totally fine with it).

**Comment by tyranron** [comment]
@r3pek thank you for feedback and tips.

This image is intended to be in production use, so I see following disadvantages in your proposal:

- Having `composer` in runtime image increases its size and gives not benefits in runtime. It can even help to simplify code injections which is additional security flaw.

- Running `composer update` in the entrypoint shell script:
    - slows down container starting time;
    - creates additional network pressure on every container start/restart;
    - allows unpredictable results in production runtime (who knows what can be suddenly updated there).

That's why, at this point, I won't do something like this, and won't recommend to anybody.

The better way is just to create your own image `FROM instrumemtisto/roundcube`, install desired plugins in the next layers, test the result, publish it, and then, just reuse solid test image for your case.

I think it should be explicitly mentioned somewhere in README.
