### ISSUE TITLE
Only add registries to NAMESPACES when credentials are provided

### ISSUE THREAD

**Issue by waja** [instrumentisto/roundcube-docker-image#12]
It would be very lovely if you could adjust `Makefile` in a way that `NAMESPACES` does not include:

* `$(OWNER)` if `secrets.DOCKERHUB_BOT_PASS` is not set
* `quay.io/$(OWNER)` if `secrets.QUAYIO_ROBOT_TOKEN` is not set

This will life make easier to work on forks and maybe contribute.

Thanks Jan

**Comment by tyranron** [comment]
@waja I've [reworked CI](https://github.com/instrumentisto/roundcube-docker-image/commit/c8a6c76712128d46eaebb73f9a594a1d1201dbad) to make it more granular. Now the only thing you need is to remove undesired registries from the `release-docker` CI job's build matrix.

After thinking about it a bit more I've decided to not operate on `secrets.*` presence, because such way is more error prone for us: if some member accidentally deletes/forgets the required secrets, we want to have an error, not just silently omit releasing it. This stake is higher for us than fork inconviences.

**Comment by waja** [comment]
The intention there was, that without changing anything an automated build of a fork (maybe just for creating a PR) will not break, when not having setup docker and qualy registry, while GHCR will work straight away, cause it's already everything in place.

**Comment by tyranron** [comment]
@waja seems that I've [figured out](https://github.com/instrumentisto/roundcube-docker-image/commit/86fa541d18c6c48653bc08dabcb1ce1ab1ee30b6) how to do it for forks only. This is a bit akward since [GitHub Actions don't allow to skip a job conditionally on a `matrix` value](https://github.community/t/matrix-cannot-be-used-in-jobs-level-if/17177), but not that much.

So everyone should be satisfied now 🙃

**Comment by waja** [comment]
@tyranron is https://github.com/waja/roundcube-docker-image/actions/runs/2576598750 like it used to be? ;)

**Comment by tyranron** [comment]
@waja could you investigate why [this condition](https://github.com/waja/roundcube-docker-image/blob/1.5.3-0.2/.github/workflows/ci.yml#L104-L110) evaluates to `false` on your pipeline?

**Comment by waja** [comment]
The only reason I could imagine would be that there are secrets set, but no.

![sec](https://user-images.githubusercontent.com/1449568/176211227-5e8d1795-4a23-459f-93c9-4dbf102909a6.png)

**Comment by tyranron** [comment]
@waja try to debug it:
```yaml
      - id: skip
        run: |
          echo ::set-output name=owner_cond::${{ github.repository_owner != 'instrumentisto' }}
          echo ::set-output name=is_quay::${{ matrix.registry == 'quay.io' }}
          echo ::set-output name=no_quay_user::${{ secrets.QUAYIO_ROBOT_USER == '' }}
          echo ::set-output name=is_dockerhub::${{ matrix.registry == 'docker.io' }}
          echo ::set-output name=no_dockerhub_user::${{ secrets.DOCKERHUB_BOT_USER == '' }}
          echo ::set-output name=quay_cond::${{ (matrix.registry == 'quay.io' && secrets.QUAYIO_ROBOT_USER == '') }}
          echo ::set-output name=dockerhub_cond::${{ (matrix.registry == 'docker.io' && secrets.DOCKERHUB_BOT_USER == '') }}
          echo ::set-output name=registry_cond::${{ ((matrix.registry == 'quay.io' && secrets.QUAYIO_ROBOT_USER == '') || (matrix.registry == 'docker.io' && secrets.DOCKERHUB_BOT_USER == '')) }}
          echo ::set-output name=full_cond::${{ 
               github.repository_owner != 'instrumentisto'
               && ((matrix.registry == 'quay.io'
                    && secrets.QUAYIO_ROBOT_USER == '')
                || (matrix.registry == 'docker.io'
                    && secrets.DOCKERHUB_BOT_USER == ''))
             }}
          echo ::set-output name=no::${{ !(
               github.repository_owner != 'instrumentisto'
               && ((matrix.registry == 'quay.io'
                    && secrets.QUAYIO_ROBOT_USER == '')
                || (matrix.registry == 'docker.io'
                    && secrets.DOCKERHUB_BOT_USER == ''))
             ) }}
```

**Comment by tyranron** [comment]
@waja actually evaluation to `false` is right. It just `false` is not evaluated correctly as a boolean expression.

**Comment by tyranron** [comment]
@waja should be fixed now, I've tested on my own fork.

**Comment by waja** [comment]
@tyranron great! After fiddling around with [pull](https://wei.github.io/pull) and reforking I was able to [successful](https://github.com/waja/roundcube-docker-image/actions/runs/2580965396) test it. I would love to have childs with you! :-)
